// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjwjticuefefpkvifoln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqd2p0aWN1ZWZlZnBrdmlmb2xuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NTc5NDAsImV4cCI6MjA3MzUzMzk0MH0.IyDkfDje-uet8ITTdGbNMCV661Ne8ccNeFymXVpXJeU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});