// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aroceggkpjvtytejcnka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFyb2NlZ2drcGp2dHl0ZWpjbmthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NDA2MDgsImV4cCI6MjA3MzQxNjYwOH0.O71gwv0Aab4SPFyJxAANDyP6UNksRYtLJlb9hXPzu6k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});